spring:
  devtools:
    livereload:
      enabled: true
  security:
    user:
      name: test
      password: 12311
  datasource:
    url: jdbc:mysql://localhost:3306/POSTBOX?serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace